[package]
name = "@terrazul/package-creator"
version = "0.0.2"
description = "Package that helps in package creation"
repository = "https://github.com/terrazul-ai/tz-packages"
license = "MIT"


[exports.claude]
template = "templates/CLAUDE.md"
subagentsDir = "templates/claude/agents"
commandsDir = "templates/claude/commands"
skillsDir = "templates/claude/skills"
mcpServers = "templates/claude/mcp_servers.json.hbs"

[metadata]
tz_spec_version = 1
